In [1]:
import os
os.getcwd()

'D:\\JupyterNotebooks'

In [3]:
!conda activate cv_env
!conda install pandas numpy matplotlib seaborn

Channels:
 - defaults
Platform: win-64
Collecting package metadata (repodata.json): ...working... done
Solving environment: ...working... done

# All requested packages already installed.

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# Set plot style for better aesthetics
sns.set(style='whitegrid')

In [4]:
import seaborn as sns
import matplotlib
import pandas as pd

print(sns.__version__)
print(matplotlib.__version__)
print(pd.__version__)

0.13.2
3.10.8
2.3.3

In [5]:
!git clone https://github.com/GeeksforgeeksDS/21-Days-21-Projects-Dataset

Cloning into '21-Days-21-Projects-Dataset'...

In [6]:
import os
os.listdir()

['.ipynb_checkpoints',
 '1050.jpg',
 '19_Autonomous_Market_Analyst_Building_AI_Agents_for_Deep_Research.ipynb',
 '1_Data_Storytelling_Analysing_Survival_on_the_Titanic.ipynb',
 '21-Days-21-Projects-Dataset',
 'anaconda_projects',
 'BasicsOfPython.ipynb',
 'EDA_Titanic.ipynb',
 'Files.ipynb',
 'Functions and String.ipynb',
 'inspirational_quotes.csv',
 'new.txt',
 'numpyarrays.ipynb',
 'Operators.ipynb',
 'practice.ipynb',
 'PythonBasics2.ipynb',
 'Untitled.ipynb',
 'Untitled1.ipynb',
 'Untitled2.ipynb',
 'Untitled3.ipynb',
 'WebScraping.ipynb']

In [7]:
os.listdir("21-Days-21-Projects-Dataset")

['.git', 'Datasets']

In [8]:
!dir

 Volume in drive D is New Volume
 Volume Serial Number is 94C1-5484

 Directory of D:\JupyterNotebooks

08-04-2026  23:47    <DIR>          .
08-04-2026  23:46    <DIR>          .ipynb_checkpoints
18-11-2025  23:19            53,966 1050.jpg
07-04-2026  18:26         2,400,875 19_Autonomous_Market_Analyst_Building_AI_Agents_for_Deep_Research.ipynb
08-04-2026  20:48         1,484,599 1_Data_Storytelling_Analysing_Survival_on_the_Titanic.ipynb
08-04-2026  23:47    <DIR>          21-Days-21-Projects-Dataset
22-07-2025  18:00    <DIR>          anaconda_projects
08-08-2025  00:30            19,706 BasicsOfPython.ipynb
08-04-2026  23:46            35,102 EDA_Titanic.ipynb
30-08-2025  00:45             1,266 Files.ipynb
18-08-2025  21:26             9,016 Functions and String.ipynb
01-09-2025  23:18            18,016 inspirational_quotes.csv
30-08-2025  00:08                81 new.txt
01-09-2025  20:24             1,536 numpyarrays.ipynb
12-08-2025  00:08             5,439 Operators.ipynb
28-08-2025  20:23            36,954 practice.ipynb
23-07-2025  16:30             6,478 PythonBasics2.ipynb
23-07-2025  21:26             3,841 Untitled.ipynb
30-08-2025  00:03               337 Untitled1.ipynb
29-09-2025  15:20            21,843 Untitled2.ipynb
18-11-2025  23:27            18,775 Untitled3.ipynb
01-09-2025  23:22           350,936 WebScraping.ipynb
              18 File(s)      4,468,766 bytes
               4 Dir(s)  174,434,136,064 bytes free

In [9]:
import os
os.listdir("21-Days-21-Projects-Dataset/Datasets")

['airline_passenger_timeseries.csv',
 'Mall_Customers.csv',
 'netflix_titles.csv',
 'readme.txt',
 'reviews.csv',
 'Titanic-Dataset.csv',
 'WA_Fn-UseC_-Telco-Customer-Churn.csv']

In [10]:
titanic_df = pd.read_csv('21-Days-21-Projects-Dataset/Datasets/Titanic-Dataset.csv')

In [11]:
titanic_df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [12]:
titanic_df.shape

(891, 12)

In [13]:
titanic_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB

In [14]:
titanic_df.describe()

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
count,891.000000,891.000000,891.000000,714.000000,891.000000,891.000000,891.000000
mean,446.000000,0.383838,2.308642,29.699118,0.523008,0.381594,32.204208
std,257.353842,0.486592,0.836071,14.526497,1.102743,0.806057,49.693429
min,1.000000,0.000000,1.000000,0.420000,0.000000,0.000000,0.000000
25%,223.500000,0.000000,2.000000,20.125000,0.000000,0.000000,7.910400
50%,446.000000,0.000000,3.000000,28.000000,0.000000,0.000000,14.454200
75%,668.500000,1.000000,3.000000,38.000000,1.000000,0.000000,31.000000
max,891.000000,1.000000,3.000000,80.000000,8.000000,6.000000,512.329200

In [15]:
titanic_df['Cabin'].value_counts()

Cabin
G6             4
C23 C25 C27    4
B96 B98        4
F2             3
D              3
              ..
E17            1
A24            1
C50            1
B42            1
C148           1
Name: count, Length: 147, dtype: int64

In [16]:
titanic_df.isna()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,False,False,False,False,False,False,False,False,False,False,True,False
1,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,True,False
3,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,True,False
...,...,...,...,...,...,...,...,...,...,...,...,...
886,False,False,False,False,False,False,False,False,False,False,True,False
887,False,False,False,False,False,False,False,False,False,False,False,False
888,False,False,False,False,False,True,False,False,False,False,True,False
889,False,False,False,False,False,False,False,False,False,False,False,False
890,False,False,False,False,False,False,False,False,False,False,True,False

Preprocessing

In [17]:
titanic_df.isna().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [18]:
median=titanic_df['Age'].median()

In [19]:
print(median)

28.0

In [20]:
titanic_df['Age'] = titanic_df['Age'].fillna(median)

In [21]:
titanic_df['Age'].isna().sum()

np.int64(0)

In [22]:
mode_embarked = titanic_df['Embarked'].mode()[0]
titanic_df['Embarked'] = titanic_df['Embarked'].fillna(mode_embarked)

In [23]:
titanic_df['Has_Cabin'] = titanic_df['Cabin'].notna().astype(int)
titanic_df.drop('Cabin', axis=1, inplace=True)

In [24]:
titanic_df.isna().sum()

PassengerId    0
Survived       0
Pclass         0
Name           0
Sex            0
Age            0
SibSp          0
Parch          0
Ticket         0
Fare           0
Embarked       0
Has_Cabin      0
dtype: int64